Evaluacion 2/Models/BancoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluacion_2.Models
{
    public class BancoViewModel
    {
        public int IdBanco { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaRegistro { get; set; }
        public string FechaRegistroStr { get; set; }
    }
}

Evaluacion 2/Models/ErrorViewModel.cs
using System;

namespace Evaluacion_2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Evaluacion 2/Models/OrdenPagoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluacion_2.Models
{
    public class OrdenPagoViewModel
    {
        public int IdOrden { get; set; }
        public string Monto { get; set; }
        public string Moneda { get; set; }
        public string Estado { get; set; }
        public DateTime FechaPago { get; set; }
        public string FechaPagoStr { get; set; }
        public int? IdSucursal { get; set; }
    }
}

Evaluacion 2/Models/SucursalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluacion_2.Models
{
    public class SucursalViewModel
    {
        public int IdSucursal { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaRegistro { get; set; }
        public string FechaRegistroStr { get; set; }
        public int IdBanco { get; set; }
    }
}

Evaluacion 2/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluacion_2.Models
{
    public class UsuarioViewModel
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public int Estado { get; set; }
        public int RolId { get; set; }
        public DateTime FechaRegistro { get; set; }
    }
}

Evaluacion 2/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Evaluacion_2.Models;

using Evaluacion_2.Services;
using Microsoft.Extensions.Configuration;
using Evaluacion_2.Filters;

namespace Evaluacion_2.Controllers
{
    [AccesFilter]
    public class BancoController : Controller
    {
        public readonly BancoService _BancoService;
        private readonly IConfiguration _configuration;

        public BancoController(IConfiguration configuration)
        {
            _configuration = configuration;
            _BancoService = new BancoService(_configuration);
        }

        public async Task<IActionResult> Index()
        {
            var Bancos = await Task.Run(() => _BancoService.GetBancos());

            return View(Bancos);
        }
    }
}

Evaluacion 2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Evaluacion_2.Models;

using Evaluacion_2.Filters;

namespace Evaluacion_2.Controllers
{
    [AccesFilter]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Evaluacion 2/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Evaluacion_2.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;

namespace Evaluacion_2.Controllers
{
    public class LoginController : Controller
    {
        public readonly UsuarioService _UsuarioService;
        private readonly IConfiguration _configuration;

        public LoginController(IConfiguration configuration)
        {
            _configuration = configuration;
            _UsuarioService = new UsuarioService(_configuration);
        }

        [HttpGet]
        public IActionResult Index()
        {
            Response.Cookies.Delete("UsuarioId");
            Response.Cookies.Delete("UsuarioNombre");
            Response.Cookies.Delete("UsuarioRolId");

            ViewBag.showSalir = false;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Acceso(string usuario, string contrasenia)
        {
            var Usuario = await Task.Run(() => _UsuarioService.GetUsuarioByParametros(usuario, contrasenia));

            if (Usuario != null)
            {
                CookieOptions options = new CookieOptions
                {
                    Expires = DateTime.Now.AddMinutes(5)
                };

                Response.Cookies.Append("UsuarioId", Usuario.IdUsuario.ToString(), options);
                Response.Cookies.Append("UsuarioNombre", Usuario.Nombre, options);
                Response.Cookies.Append("UsuarioRolId", Usuario.RolId.ToString(), options);
                
                return RedirectToAction("index", "home");
            }
            else
            {
                return RedirectToAction("index", "Login");
            }
        }

        public ActionResult Salir(string usuario, string contrasenia)
        {
            Response.Cookies.Delete("UsuarioId");
            Response.Cookies.Delete("UsuarioNombre");
            Response.Cookies.Delete("UsuarioRolId");

            return RedirectToAction("index", "login");
        }
    }
}

Evaluacion 2/Controllers/OrdenPagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Evaluacion_2.Models;

using Evaluacion_2.Services;
using Microsoft.Extensions.Configuration;
using Evaluacion_2.Filters;

namespace Evaluacion_2.Controllers
{
    [AccesFilter]
    public class OrdenPagoController : Controller
    {
        public readonly OrdenPagoService _OrdenPagoService;
        private readonly IConfiguration _configuration;

        public OrdenPagoController(IConfiguration configuration)
        {
            _configuration = configuration;
            _OrdenPagoService = new OrdenPagoService(_configuration);
        }

        public async Task<IActionResult> Index(int IdSucursal)
        {
            var Ordenes = await Task.Run(() => _OrdenPagoService.GetOrdenPagobyIdSucursal(IdSucursal));

            return View(Ordenes);
        }
    }
}

Evaluacion 2/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Evaluacion_2.Models;

using Evaluacion_2.Services;
using Microsoft.Extensions.Configuration;
using Evaluacion_2.Filters;

namespace Evaluacion_2.Controllers
{
    [AccesFilter]
    public class SucursalController : Controller
    {
        public readonly SucursalService _SucursalService;
        private readonly IConfiguration _configuration;

        public SucursalController(IConfiguration configuration)
        {
            _configuration = configuration;
            _SucursalService = new SucursalService(_configuration);
        }

        public async Task<IActionResult> Index(int IdBanco)
        {
            var sucursales = await Task.Run(() => _SucursalService.GetSucursalesbyIdBanco(IdBanco));

            return View(sucursales);
        }
    }
}

Evaluacion 2/Views/Banco/Index.cshtml
@model List<BancoViewModel>
@{
    ViewData["Title"] = "Bancos";
}

<h2>Bancos</h2>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Nombre</td>
            <td>Dirección</td>
            <td>FechaRegistro</td>
            <td>Ver Sucursales</td>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.IdBanco</td>
            <td>@item.Nombre</td>
            <td>@item.Direccion</td>
            <td>@item.FechaRegistro.ToShortDateString()</td>
            <td><a href="@Url.Action("Index", "Sucursal", new { IdBanco = item.IdBanco })">Ver</a></td>
        </tr>
    }
    </tbody>
</table>

Evaluacion 2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<h2>Bienvenido al Sistema de Bancos del Comercio</h2>

<hr />
<p>Echa un vistazo a los enlaces del Menú</p>
<br />
<div class="">
    <environment include="Development">
        <img src="~/images/img1.png" class="img-responsive center-block" alt="Negocio" />
    </environment>
</div>

Evaluacion 2/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}

<h2>Ingrese sus datos</h2>

@using (Html.BeginForm("Acceso", "Login", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="">
    <label for="uname"><b>Usuario</b></label>
    <input type="text" name="usuario" class="form-control" value="" placeholder="Ingrese usuario" />

    <label for="uname"><b>Contraseña</b></label>
    <input type="password" name="contrasenia" class="form-control" value="" placeholder="Ingrese contraseña" />
</div>
    <br />
<div>
    <button type="submit">Ingresar</button>
</div>
}

Evaluacion 2/Views/OrdenPago/Index.cshtml
@model List<OrdenPagoViewModel>
@{
    ViewData["Title"] = "Orden de Pago";
}

<h2>Ordenes de Pago</h2>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Monto</td>
            <td>Moneda</td>
            <td>Estado</td>
            <td>Fecha Pago</td>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.IdOrden</td>
            <td>@item.Monto</td>
            <td>@item.Moneda</td>
            <td>@item.Estado</td>
            <td>@item.FechaPago.ToShortDateString()</td>
        </tr>
    }
    </tbody>
</table>

Evaluacion 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - El Comercio</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">El Comercio</a>
            </div>
            @if (ViewBag.showSalir == null)
            {
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Banco" asp-action="index">Bancos</a></li>
                    <li><a asp-area="" asp-controller="Sucursal" asp-action="index">Sucursales</a></li>
                    <li><a asp-area="" asp-controller="OrdenPago" asp-action="index">Ordenes de Pago</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Login" asp-action="salir">Salir</a></li>
                </ul>
            </div>
            }
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - El Comercio</p>
            <p>Desarrollado por <a href="https://github.com/linkinrodx/" target="_blank">Rodrigo Saraya</a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Evaluacion 2/Views/Sucursal/Index.cshtml
@model List<SucursalViewModel>
@{
    ViewData["Title"] = "Sucursales";
}

<h2>Sucursales</h2>

<table class="table">

    <thead>
        <tr>
            <td>Id</td>
            <td>Nombre</td>
            <td>Dirección</td>
            <td>FechaRegistro</td>
            <td>Ver Ordenes Pago</td>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.IdSucursal</td>
            <td>@item.Nombre</td>
            <td>@item.Direccion</td>
            <td>@item.FechaRegistro.ToShortDateString()</td>
        <td><a href="@Url.Action("Index", "OrdenPago", new { IdSucursal = item.IdSucursal })">Ver</a></td>
        </tr>
    }
    </tbody>
        
</table>